name: LaravelTwitch

on:
  push:
    branches: [ master ]


jobs:
  laravel-test:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v2
  - name: Example
    run: echo "Hello"
  - name: Example2
    run: echo "Hello2"
